### ISSUE TITLE
Hello ！！ how to use convtool ？IN Chinese。。。。。。

### ISSUE THREAD

**Issue by yanghedada** [walkerning/compression-tool#1]
作者你好，不好意思英文太烂，只能用中文了，关于convtool的使用。

```
  pipeline:
    - conv

  config:
    conv:
      command: 'conv_tool'
      input_proto: '/home/yanghe/Desktop/model/origin/Model.prototxt'
      input_caffemodel: '/home/yanghe/Desktop/model/origin/Model.caffemodel'
      output_proto: '/home/yanghe/Desktop/model/compress/Model.prototxt'
      output_caffemodel: '/home/yanghe/Desktop/model/compress/Model.caffemodel'
      mode:
        compression_specification:
          conv1_2_2: 10

```

直接从中间开始减发现没有bottom,

![image](https://user-images.githubusercontent.com/37058860/56271180-6c007200-612a-11e9-9727-a30230dc2be4.png)

如果
```
compression_specification:
          conv1_2_2: 10
          conv1_2_1: 10
```
就会：
![image](https://user-images.githubusercontent.com/37058860/56271261-a538e200-612a-11e9-8d85-3483875d6a6e.png)

![image](https://user-images.githubusercontent.com/37058860/56271028-16c46080-612a-11e9-87df-ba428fce5ce8.png)
